# Base packages to scan Dubbo Component: @org.apache.dubbo.config.annotation.Service
dubbo:
  scan:
    base-packages: com.daniellin07.dubboscaffold.web.service

  # Dubbo Application
  ## The default value of dubbo.application.name is ${spring.application.name}
  ## dubbo.application.name=${spring.application.name}

  # Dubbo Protocol
  protocol:
    name: dubbo
    port: 20802

  ## Dubbo Registry
  registry:
    address: nacos://127.0.0.1:8848

nacos:
  config:
    server-addr: 127.0.0.1:8848